version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:

# Exercise: Infrastructure Creation
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
      - run: 
          name: Get Ansible Inventory
          command: echo "[all]\r\n" > ~/inventory.txt && sleep 10 && aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/inventory.txt
          when: on_success
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory.txt

# Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["e9:6e:72:68:47:5d:89:5a:ae:b0:75:9b:35:d9:16:05"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - attach_workspace:
          at: ~/
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i ~/inventory.txt main.yml

workflows:
  my_workflow:
      jobs:
        - create_infrastructure
        - configure_infrastructure:
            requires:
            - create_infrastructure