version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:

# Exercise: Infrastructure Creation
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
      - run: 
          name: Get Ansible Inventory
          command: sleep 15 && aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/inventory
          when: on_success
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory

# Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["2a:6d:cb:05:3f:4b:aa:47:d4:54:63:6e:63:2b:4d:3d"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - attach_workspace:
          at: ~/
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i ~/inventory main.yml --private-key ~/.ssh/id_rsa_2a6dcb053f4baa47d454636e632b4d3d

workflows:
  my_workflow:
      jobs:
        - create_infrastructure
        - configure_infrastructure:
            requires:
            - create_infrastructure